### ISSUE TITLE
Bamboo Variables being substituted during seed task.

### ISSUE THREAD

**Issue by mayani** [mibexsoftware/bamboo-plan-dsl-plugin#39]
### Add On Verison

1.8.2

### Sample Input

```yaml
                - !script
                  description: Unit Tests
                  inlineScript:
                    interpreter: !scriptInterpreter LEGACY_SH_BAT
                    scriptBody: |
                      TAG=${bamboo.build.working.directory}
                      echo $TAG
```

### Description

The variable bamboo.build.working.directory is being substituted while running the seed task i.e. The task is created with the `hard-coded` value of the working directory of the seed task. The variable value should not be substituted during the seed task.

### Sample Output

Value of the TAG variable is working directory of the seed task.
