### ISSUE TITLE
YAML Issue with Permissions (userType) Section

### ISSUE THREAD

**Issue by mayani** [mibexsoftware/bamboo-plan-dsl-plugin#43]
### Add On Verison

1.8.2

### Sample Input

```yaml
        other: !userType
          ANONYMOUS_USERS: !permission VIEW
          LOGGED_IN_USERS: !permission VIEW
```

### Description

Exception while saving definition.

### Stack Trace

```
Invalid YAML syntax: Can't construct a java object for !userType; exception=java.lang.NoSuchMethodException: ch.mibex.bamboo.plandsl.dsl.permissions.Permissions$OtherUserType.<init>() in 'string', line 15, column 16: other: !userType ^
```
