### ISSUE TITLE
IGNORE action not being respected for permissions

### ISSUE THREAD

**Issue by mayani** [mibexsoftware/bamboo-plan-dsl-plugin#47]
### Add On Verison

1.8.2

### Sample Input

Action for not-referenced Bamboo objects: IGNORE

```yaml
project:
  key: DSLT
  name: DSLT
  plans:
    - key: BNT47
      name: Build & Test
      stages:
        - name: Source Checkout
          jobs:
            - key: DIST
              name: Source checkout and distribution
              description: Create the full distribution tarball
              enabled: false
              tasks:
                - !script
                  description: Create source tarballs
                  inlineScript:
                    interpreter: !scriptInterpreter LEGACY_SH_BAT
                    scriptBody: "echo A"
              miscellaneous:
                cleanWorkingDirectoryAfterEachBuild: true
```

Manually modify plan permissions.

### Permissions

When the YAML spec. does not include `permissions` section, running the seed task always clears out the plan's permissions section, even when Action for not-referenced Bamboo objects is set to `IGNORE`.
