### ISSUE TITLE
Unable to create customNotification

### ISSUE THREAD

**Issue by mayani** [mibexsoftware/bamboo-plan-dsl-plugin#91]
Type: Bug
Version: 1.9.14
Format: YAML
Uses: Slack Plugin: Slack Notifications for Bamboo (com.atlassian.bamboo.plugins.bamboo-slack)
Seed plan succeeds, but does not add the notification.

```yaml
      notifications:
        - !customNotification
          event: !event JOB_HUNG
          notificationRecipientType: 'com.atlassian.bamboo.plugins.bamboo-slack:recipient.slack'
          config:
            webhookUrl: ['URL']
            channel: ['#channel]
            botName: null
            botName: [Bamboo]
```

**Comment by mrueegg** [comment]
Hi,

First, please excuse my very late response.

Unfortunately, I wasn't able to reproduce this problem. Here's my test case:

```yaml
project:
  key: TEST
  name: TEST
  plans:
    - key: TEST
      name: TEST
      description: test
      notifications:
        - !customNotification
          event: !event JOB_HUNG
          notificationRecipientType: 'com.atlassian.bamboo.plugins.bamboo-slack:recipient.slack'
          config:
            webhookUrl: ['URL']
            channel: [channel]
            botName: [Bamboo]
```

The only difference I could spot is that you are missing the closing single quote in the `channel` field and that you have a duplicate `botName` definition. Does that help?

Best regards,
Michael
